version: "3.8"
services:
  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3007:3007"
    depends_on:
      - postgres
  product:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
    depends_on:
      - mongo
  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  mongo:
    image: mongo:4
volumes:
  postgres_data:
  mongo_data:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
